drop_x = "50"
drop_y = "50"
drop_salt = "0x0000000000000000000000000000000000000000000000000000000000000001"
session_id = "1"
turn = "1"
ping_x = "50"
ping_y = "50"
expected_commitment = "0x0"
expected_distance = "0"
