[package]
name = "dead-drop-proof-methods"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "3.0.4", default-features = false }

[build-dependencies]
risc0-build = "3.0.4"

[package.metadata.risc0]
methods = ["guest"]
