[package]
name = "dead-drop-proof-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "3.0.4", default-features = false }
sha2 = { version = "0.10.8", default-features = false }
